/**
 *
 */
package ch.epfl.smartmap.servercom;



/**
 * A client object to a SwEng quiz server that abstracts the underlying communication protocol and data formats.
 *
 * @author SpicyCH
 */
public interface SmartMapClient {

    /**
     * The different connection status. Only CONNECTION_SUCCESS is a success,
     * all other status are different erros.
     *
     * @author SpicyCH
     */
    public enum ConnectionStatus {
        CONNECTION_SUCCESS, CONNECTION_FAILED, MALFORMED_URL
    }

    /**
     *
     * @param hash the hash stored locally on the device
     * @param phoneNumber the user's phone number, which can be editable in the GUI
     * @author SpicyCH
     */
    void authRequest(String hash, String phoneNumber);

    /**
     * Generates a new unique hash, not dependent on the phone number.
     * @param phoneNumber the phone number
     * @return
     * @author SpicyCH
     */
    String getNewHash(String phoneNumber);

    /**
     * Checks whether or not the sms code given by the user matches the one generated by the nexmo's SMS server.
     * @param hash the sha-256 hash
     * @param codeSMS the code sent to the user's phone
     * @return
     * @author SpicyCH
     */
    ConnectionStatus verifySMSCode(String hash, String codeSMS);
}